basic:
    name: 'Dr. Roberta Ankunding'
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - 'https://www.hand.com/error-molestiae-sit-inventore'
        - 'https://www.langosh.net/est-velit-eaque-et-non'
    monitoring:
        days: {  }
        type: ''
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
